"""CLOB V2 order-signing known-answer contracts.

Ground truth pinned 2026-07-18 from:
- https://docs.polymarket.com/v2-migration (struct semantics, domain version)
- https://docs.polymarket.com/resources/contracts (addresses incl. pUSD)
- github.com/Polymarket/py-clob-client-v2 @ main — the reference
  implementation the exchange accepts in production. Its
  `exchange_order_builder_v2.py` type string WINS over docs prose (the docs
  page misplaces `signatureType`; the implementation puts it after `side`).

The KNOWN-ANSWER vectors below were generated by running the official
py-clob-client-v2 `ExchangeOrderBuilderV2` with the public Hardhat dev key,
a fixed salt, and a fixed timestamp. Our builder must reproduce them
byte-for-byte.
"""

import secrets
from decimal import Decimal
from types import SimpleNamespace

import pytest

from polymarket.trading import order_builder as order_builder_module
from polymarket.models import OrderRequest, OrderType, Side
from polymarket.exceptions import ValidationError
from polymarket.trading.order_builder import (
    COLLATERAL_TOKEN,
    EXCHANGE_ADDRESS,
    NEG_RISK_EXCHANGE_ADDRESS,
    ORDER_STRUCT,
    ORDER_TYPE_STRING,
    V2_DOMAIN_NAME,
    V2_DOMAIN_VERSION,
    OrderBuilder,
)

# --- pinned constants (sources above) --------------------------------------

CTF_EXCHANGE_V2 = "0xE111180000d2663C0091e4f400237545B87B996B"
NEG_RISK_CTF_EXCHANGE_V2 = "0xe2222d279d744050d28e00520010520000310F59"
PUSD = "0xC011a7E12a19f7B1f670d46F03B03f3342E82DFB"

PINNED_TYPE_STRING = (
    "Order(uint256 salt,address maker,address signer,uint256 tokenId,"
    "uint256 makerAmount,uint256 takerAmount,uint8 side,uint8 signatureType,"
    "uint256 timestamp,bytes32 metadata,bytes32 builder)"
)

# Public Hardhat/Anvil dev key #0 — never holds funds.
DEV_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEV_ADDR = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
FIXED_SALT = 479249096354
FIXED_TS = 1_784_500_000_000

VECTOR_STD_BUY_EOA = {
    "order_hash": "0x7b7e51073760ead2e85a6386301e730533fd29f58add3ca2bcef00f9ab8381c5",
    "signature": (
        "0x3a79e46d698739ea27652f5244f433ab5e5f09385f69a26ca9cde6e1ba63338c"
        "029ce64f4e09a53b90d03014b0e25b425119942cd21af734baf596ec8fb8507f1b"
    ),
}
VECTOR_NEGRISK_SELL_PROXY = {
    "maker": "0x1111111111111111111111111111111111111111",
    "order_hash": "0x23291e74b89f8b73a37468c01df7d907c541defaaeafe38a67184cff4bdc5910",
    "signature": (
        "0x3c6d39a4fa1d2cf7b0834b1ed1b7ed3a19eed9a05c907da8d5b8c262c2491c6e"
        "418b2a97cea5cf45afcc37fda837b179ba9d906e4d645017f1362e4fecfd10d61c"
    ),
}
VECTOR_POLY_1271 = {
    "maker": "0x1111111111111111111111111111111111111111",
    "signature": (
        "0xa3a093c83b6c20c83355c16ce94c92e6e9fcbdeb840618cc74f6c57a42ad145b"
        "2b98db73d2c73cbf1f2b6af288566ae81960ddbc3a13921027358a8bff3be6ff1c"
        "a440cbd865bc0c6243d7a8df9a8bf48a8827b0a4abbb61c30e96d305423af148"
        "d23d42d3ad94e65d78258cecaf8dcbaddac0f73dc085040f2c12bb595dd83804"
        "4f726465722875696e743235362073616c742c61646472657373206d616b65722c"
        "61646472657373207369676e65722c75696e7432353620746f6b656e49642c75"
        "696e74323536206d616b6572416d6f756e742c75696e743235362074616b6572"
        "416d6f756e742c75696e743820736964652c75696e7438207369676e61747572"
        "65547970652c75696e743235362074696d657374616d702c6279746573333220"
        "6d657461646174612c62797465733332206275696c6465722900ba"
    ),
}


def _buy_request():
    return OrderRequest(
        token_id="1234567890",
        price=Decimal("0.45"),
        size=Decimal("10"),
        side=Side.BUY,
        order_type=OrderType.GTC,
    )


def _sell_request():
    return OrderRequest(
        token_id="1234567890",
        price=Decimal("0.45"),
        size=Decimal("10"),
        side=Side.SELL,
        order_type=OrderType.GTC,
    )


# --- constants stay pinned ---------------------------------------------------


def test_type_string_is_pinned():
    assert ORDER_TYPE_STRING == PINNED_TYPE_STRING


def test_type_string_matches_struct_list():
    derived = (
        "Order(" + ",".join(f"{f['type']} {f['name']}" for f in ORDER_STRUCT) + ")"
    )
    assert derived == ORDER_TYPE_STRING


def test_domain_and_addresses_are_v2():
    assert V2_DOMAIN_NAME == "Polymarket CTF Exchange"
    assert V2_DOMAIN_VERSION == "2"
    assert EXCHANGE_ADDRESS == CTF_EXCHANGE_V2
    assert NEG_RISK_EXCHANGE_ADDRESS == NEG_RISK_CTF_EXCHANGE_V2
    assert COLLATERAL_TOKEN == PUSD


# --- known answers -----------------------------------------------------------


def _build(builder_kwargs, order, **kwargs):
    builder = OrderBuilder(**builder_kwargs)
    return builder.build_order(
        order=order,
        private_key=DEV_KEY,
        address=DEV_ADDR,
        nonce=0,
        tick_size=Decimal("0.01"),
        fee_rate_bps=0,
        salt_override=FIXED_SALT,
        timestamp_ms=FIXED_TS,
        **kwargs,
    )


def test_known_answer_standard_buy_eoa():
    signed = _build({}, _buy_request(), neg_risk=False, signature_type=0)
    assert signed["salt"] == FIXED_SALT
    assert signed["maker"] == DEV_ADDR
    assert signed["signer"] == DEV_ADDR
    assert signed["tokenId"] == "1234567890"
    assert signed["makerAmount"] == "4500000"
    assert signed["takerAmount"] == "10000000"
    assert signed["side"] == "BUY"
    assert signed["signatureType"] == 0
    assert signed["timestamp"] == str(FIXED_TS)
    assert signed["expiration"] == "0"
    assert signed["metadata"] == "0x" + "00" * 32
    assert signed["builder"] == "0x" + "00" * 32
    assert signed["signature"] == VECTOR_STD_BUY_EOA["signature"]
    assert signed["_orderHash"] == VECTOR_STD_BUY_EOA["order_hash"]


def test_known_answer_negrisk_sell_proxy():
    signed = _build(
        {},
        _sell_request(),
        neg_risk=True,
        signature_type=1,
        funder=VECTOR_NEGRISK_SELL_PROXY["maker"],
    )
    assert signed["maker"] == VECTOR_NEGRISK_SELL_PROXY["maker"]
    assert signed["signer"] == DEV_ADDR
    assert signed["makerAmount"] == "10000000"
    assert signed["takerAmount"] == "4500000"
    assert signed["side"] == "SELL"
    assert signed["signatureType"] == 1
    assert signed["signature"] == VECTOR_NEGRISK_SELL_PROXY["signature"]
    assert signed["_orderHash"] == VECTOR_NEGRISK_SELL_PROXY["order_hash"]


def test_poly_1271_order_uses_deposit_wallet_identity_and_wrapped_signature():
    signed = _build(
        {},
        _sell_request(),
        neg_risk=False,
        signature_type=3,
        funder="0x2222222222222222222222222222222222222222",
    )
    assert signed["signatureType"] == 3
    assert signed["maker"] == "0x2222222222222222222222222222222222222222"
    assert signed["signer"] == signed["maker"]
    assert len(signed["signature"]) > 132


def test_poly_1271_known_answer_matches_official_v1_1_vector():
    builder = OrderBuilder(chain_id=80002)
    typed_data = builder._build_typed_data(
        exchange=CTF_EXCHANGE_V2,
        salt=FIXED_SALT,
        maker=VECTOR_POLY_1271["maker"],
        signer=VECTOR_POLY_1271["maker"],
        token_id=1234,
        maker_amount=100_000_000,
        taker_amount=50_000_000,
        side=0,
        signature_type=3,
        timestamp=1_710_000_000_000,
    )
    signature, _ = builder._sign_typed_data(typed_data, DEV_KEY)
    assert signature == VECTOR_POLY_1271["signature"]


def test_poly_1271_requires_deposit_wallet_funder():
    with pytest.raises(ValidationError, match="deposit-wallet funder"):
        _build({}, _buy_request(), neg_risk=False, signature_type=3)


# --- wire shape --------------------------------------------------------------


def test_wire_dict_has_exactly_the_v2_fields():
    signed = _build({}, _buy_request(), neg_risk=False, signature_type=0)
    public_keys = {k for k in signed if not k.startswith("_")}
    assert public_keys == {
        "salt",
        "maker",
        "signer",
        "tokenId",
        "makerAmount",
        "takerAmount",
        "side",
        "expiration",
        "signatureType",
        "timestamp",
        "metadata",
        "builder",
        "signature",
    }


def test_v1_fields_are_gone():
    signed = _build({}, _buy_request(), neg_risk=False, signature_type=0)
    for legacy in ("nonce", "feeRateBps", "taker"):
        assert legacy not in signed


def test_gtd_expiration_rides_the_wire_but_not_the_signature():
    """Same signing inputs ± expiration → same signature (expiration unsigned)."""
    gtc = _build({}, _buy_request(), neg_risk=False, signature_type=0)
    gtd_request = _buy_request()
    gtd_request.order_type = OrderType.GTD
    gtd_request.expiration = 1_790_000_000
    gtd = _build({}, gtd_request, neg_risk=False, signature_type=0)
    assert gtd["expiration"] == "1790000000"
    assert gtd["signature"] == gtc["signature"]
    assert gtd["_orderHash"] == gtc["_orderHash"]


def test_deterministic_salt_from_idempotency_key_is_js_safe():
    builder = OrderBuilder()
    salt = builder.generate_salt_from_key("some-uuid")
    assert 0 <= salt < 2**32
    assert salt == builder.generate_salt_from_key("some-uuid")


def _build_retry_identity(idempotency_key, *, timestamp_ms=None):
    return OrderBuilder().build_order(
        order=_buy_request(),
        private_key=DEV_KEY,
        address=DEV_ADDR,
        nonce=0,
        tick_size=Decimal("0.01"),
        fee_rate_bps=0,
        idempotency_key=idempotency_key,
        timestamp_ms=timestamp_ms,
    )


def test_idempotency_key_keeps_creation_timestamp_on_wall_clock(monkeypatch):
    monkeypatch.setattr(
        order_builder_module,
        "time",
        SimpleNamespace(time_ns=lambda: 1_800_000_000_001_000_000),
    )

    signed = _build_retry_identity("copy-command-123")

    assert signed["timestamp"] == "1800000000001"
    assert signed["salt"] == OrderBuilder().generate_salt_from_key("copy-command-123")


def test_explicit_timestamp_is_used_with_idempotency_key():
    signed = _build_retry_identity(
        idempotency_key="copy-command-123",
        timestamp_ms=FIXED_TS,
    )

    assert signed["timestamp"] == str(FIXED_TS)


def test_explicit_timestamp_and_key_pin_full_v2_retry_identity():
    first = _build_retry_identity(
        "copy-command-123",
        timestamp_ms=FIXED_TS,
    )
    retried = _build_retry_identity(
        "copy-command-123",
        timestamp_ms=FIXED_TS,
    )

    assert first["timestamp"] == retried["timestamp"]
    assert first["salt"] == retried["salt"]
    assert first["_orderHash"] == retried["_orderHash"]
    assert first["signature"] == retried["signature"]


def test_keyless_order_keeps_random_salt_and_wall_clock_timestamp(monkeypatch):
    timestamps_ns = iter(
        [
            1_800_000_000_001_000_000,
            1_800_000_000_002_000_000,
        ]
    )
    salts = iter([111, 222])
    monkeypatch.setattr(
        order_builder_module,
        "time",
        SimpleNamespace(time_ns=lambda: next(timestamps_ns)),
    )
    monkeypatch.setattr(secrets, "randbits", lambda bits: next(salts))

    first = _build_retry_identity(None)
    second = _build_retry_identity(None)

    assert first["timestamp"] == "1800000000001"
    assert second["timestamp"] == "1800000000002"
    assert first["salt"] == 111
    assert second["salt"] == 222
    assert first["_orderHash"] != second["_orderHash"]


# --- tick-size rounding (C2 carry, adopted proactively) ----------------------


def test_fine_tick_preserves_usd_precision():
    """tick 0.001 → USD side keeps 5 decimals; the old fixed 4dp misrounded."""
    from polymarket.trading.order_builder import _divisors_for_tick

    assert _divisors_for_tick(Decimal("0.001")) == (10_000, 10)
    assert _divisors_for_tick(Decimal("0.01")) == (10_000, 100)
    assert _divisors_for_tick(Decimal("0.1")) == (10_000, 1_000)
    with pytest.raises(ValidationError, match="Unsupported CLOB tick size"):
        _divisors_for_tick(Decimal("0.02"))


def test_fine_tick_buy_amounts_are_exact():
    builder = OrderBuilder()
    order = OrderRequest(
        token_id="1234567890",
        price=Decimal("0.123"),
        size=Decimal("0.33"),
        side=Side.BUY,
        order_type=OrderType.GTC,
    )
    signed = builder.build_order(
        order=order,
        private_key=DEV_KEY,
        address=DEV_ADDR,
        tick_size=Decimal("0.001"),
        salt_override=FIXED_SALT,
        timestamp_ms=FIXED_TS,
    )
    assert signed["takerAmount"] == "330000"  # 0.33 tokens
    # 0.33 × 0.123 = 0.04059 → 40590 atomic units, exact under 5dp rounding
    # (the old fixed 4dp floor would have produced 40500 — a mispriced order).
    assert signed["makerAmount"] == "40590"
